### PR TITLE
Add support for Arch Linux

### PR DESCRIPTION
**Pull request by chivongv**

### CODE REVIEW

**Comment by tmds** [comment]
@chivongv thanks for adding Arch support!

I've been looking to find some documentation, and I came across: https://archlinux.org/news/ca-certificates-update/

Can you change the PR to what is described there, and see if it still works for you?

- `/etc/ca-certificates/trust-source/anchors/` as the `ArchFamilyCaSourceDirectory`
- `crt` as the extension
- [ `trust`, `extract-compat`] as the `trustCommand`. The `trust` executable is from the `p11-kit` package.

**Comment by tmds** [comment]
> If you want, I can push up the changes.

Yes, please push those changes. I prefer the "documented" approach.

> Neither solutions worked with Brave browser.

Unfortunately some browsers have their own opinion of what to trust. :/

**Comment by amcasey** [comment]
> @chivongv thanks for adding Arch support!
> 
> I've been looking to find some documentation, and I came across: https://archlinux.org/news/ca-certificates-update/
> 
> Can you change the PR to what is described there, and see if it still works for you?
> 
> * `/etc/ca-certificates/trust-source/anchors/` as the `ArchFamilyCaSourceDirectory`
> * `crt` as the extension
> * [ `trust`, `extract-compat`] as the `trustCommand`. The `trust` executable is from the `p11-kit` package.

I haven't tried it (yet), but [this page](https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate) makes it sound like you can use `update-ca-trust extract`, as on fedora.  Maybe that's equivalent to `trust extract-compat`?

**Comment by tmds** [comment]
> I haven't tried it (yet), but [this page](https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate) makes it sound like you can use update-ca-trust extract, as on fedora. Maybe that's equivalent to trust extract-compat?

What we have now is described here: https://archlinux.org/news/ca-certificates-update/ and it seems to do what we need.

It's not clear if what is described on that page would be better, so I think we can go with what we have now.

**Comment by tmds** [comment]
Thanks @chivongv!

I'll include this in a release tomorrow.

**Comment by chivongv** [comment]
@tmds Cheers! Thanks!

Note that https://archlinux.org/news/ca-certificates-update/ is from 2014. I don't know if things have changed or not. Like you said, we can go with what we have now and see.

**Comment by amcasey** [comment]
> @tmds Cheers! Thanks!
> 
> Note that https://archlinux.org/news/ca-certificates-update/ is from 2014. I don't know if things have changed or not. Like you said, we can go with what we have now and see.

I did some quick tests in docker and it seems to work.

**Pull request merged**
